export const background_color = '#0f0f0f'
export const text_color = ''
export const transaction_details_bg_color = '#FFF1F1'
export const cancel_button_color = '#00693e'
export const delete_button_color = '#de1738'
export const received_color = '#F2FBF5'
export const padi_color = '#FFF1F1'